<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rules</string>
	</array>
	<key>name</key>
	<string>Snort</string>
	<key>patterns</key>
	<array>
		<dict>
                        <key>match</key>
                        <string>alert|log|pass|activate|dynamic|drop|reject|sdrop</string>
                        <key>name</key>
                        <string>constant.character.snortrules</string>
                </dict>
		<dict>
			<key>match</key>
			<string>any</string>
			<key>name</key>
			<string>string.unquoted.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>tcp|udp|icmp</string>
			<key>name</key>
			<string>string.unquoted.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$HOME_NET|\$EXTERNAL_NET|\$HTTP_SERVERS|\$HTTP_PORTS|\$SMTP_SERVERS|\$SQL_SERVERS|\$TELNET_SERVERS|\$SSH_SERVERS|\$FTP_SERVERS|\$SIP_SERVERS|\$SHELLCODE_PORTS|\$ORACLE_PORTS|\$SSH_PORTS|\$FTP_PORTS|\$SIP_PORTS|\$FILE_DATA_PORTS|\$GTP_PORTS|\$AIM_SERVERS|</string>
			<key>name</key>
			<string>keyword.other.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#(.*)</string>
			<key>name</key>
			<string>comment.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>msg:|flow:|flowbits:|content:|fastpattern:|metadata:|classtype:|nocase|pcre:|reference:|sid:|gid:|priority|depth:|offset:|byte_test:|within:|distance:|rev:|uricontent:|rawbytes:|byte_jump:|isdataat:|ftpbounce:|asn1:|cvs:|dce_iface:|dce_opnum:|dce_stub_data:|sip_method:|sip_stat_code:|sip_header:|sip_body:|gtp_type:|gtp_info:|gtp_version:|fragoffset:|ttl:|tos:|id:|ipopts:|fragbits:|dsize:|flags:|seq:|ack:|window:|itype:|icode:|icmp_id:|icmp_seq:|rpc:|ip_proto:|sameip:|logto:|session:|resp:|react:|tag:|activates:|activated_by:|count:|replace:|detection_filter:|threshold:</string>
			<key>name</key>
			<string>constant.character.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
			<key>name</key>
			<string>constant.numeric.snortrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
			<key>name</key>
			<string>constant.numeric.snortrules</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.snortrules</string>
	<key>uuid</key>
	<string>704158e8-8ee3-4297-b0ae-cfd55388ab03</string>
</dict>
</plist>
